name: Minecraft Data release
on:
  push:
    branches: [ test ]
  repository_dispatch:
    types: [mcData-release]
jobs:
  update-mcdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update minecraft data
        run: 'cd minecraft-data/ && git fetch --all --tags && git checkout 2.74.0'
      - name: Update package.json
        run: >
          sed -i -E 's/^  "version": "[0-9]+\.[0-9]+\.[0-9]+"/  "version": "2.74.0"/g' package.json
      - name: Update doc/history.md
        run: echo -e "## 2.74.0\n * update mcdata\n\n$(cat doc/history.md)" > doc/history.md
      - name: Create commits
        run: |
          git config user.name 'rom1504bot'
          git config user.email 'rom1504bot@users.noreply.github.com'
          git add minecraft-data
          git commit -m "Update Minecraft Data"
          git add package.json doc/history.md
          git commit -m "Release 2.74.0"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT_PASSWORD }}
          committer: rom1504bot <rom1504bot@users.noreply.github.com>
          author: rom1504bot <rom1504bot@users.noreply.github.com>
          signoff: false
          branch: release-2.74.0
          delete-branch: true
          title: 'Release 2.74.0'
          body: |
            A new version of minecraft-data was released.