name: 'trigger'
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of the release'
        required: true
        default: '2.75.0'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT_PASSWORD }}
        event-type: mcData-release
        client-payload: '{"tag": "${{ github.event.inputs.tag }}"}'
